call .\gradlew.bat :core:utils:publish
call .\gradlew.bat :core:publish
call .\gradlew.bat :advertising:publish
call .\gradlew.bat :descriptor:u2900:publish
call .\gradlew.bat :descriptor:u2901:publish
call .\gradlew.bat :descriptor:u2902:publish
call .\gradlew.bat :descriptor:u2903:publish
call .\gradlew.bat :descriptor:u2904:publish
call .\gradlew.bat :descriptor:u2905:publish
call .\gradlew.bat :descriptor:u2906:publish
call .\gradlew.bat :descriptor:u2907:publish
call .\gradlew.bat :descriptor:u2908:publish
call .\gradlew.bat :descriptor:u2909:publish
call .\gradlew.bat :descriptor:u290a:publish
call .\gradlew.bat :descriptor:u290b:publish
call .\gradlew.bat :descriptor:u290c:publish
call .\gradlew.bat :descriptor:u290d:publish
call .\gradlew.bat :descriptor:u290e:publish
call .\gradlew.bat :descriptor:u290f:publish
call .\gradlew.bat :descriptor:publish

call .\gradlew.bat :characteristic:core:publish
call .\gradlew.bat :characteristic:u2a00:publish
call .\gradlew.bat :characteristic:u2a01:publish
call .\gradlew.bat :characteristic:u2a02:publish
call .\gradlew.bat :characteristic:u2a03:publish
call .\gradlew.bat :characteristic:u2a04:publish
call .\gradlew.bat :characteristic:u2a05:publish
call .\gradlew.bat :characteristic:u2a06:publish
call .\gradlew.bat :characteristic:u2a07:publish
call .\gradlew.bat :characteristic:u2a08:publish
call .\gradlew.bat :characteristic:u2a09:publish
call .\gradlew.bat :characteristic:u2a0a:publish
call .\gradlew.bat :characteristic:u2a0c:publish
call .\gradlew.bat :characteristic:u2a0d:publish
call .\gradlew.bat :characteristic:u2a0e:publish
call .\gradlew.bat :characteristic:u2a0f:publish
call .\gradlew.bat :characteristic:u2a11:publish
call .\gradlew.bat :characteristic:u2a12:publish
call .\gradlew.bat :characteristic:u2a13:publish
call .\gradlew.bat :characteristic:u2a14:publish
call .\gradlew.bat :characteristic:u2a16:publish
call .\gradlew.bat :characteristic:u2a17:publish
call .\gradlew.bat :characteristic:u2a18:publish
call .\gradlew.bat :characteristic:u2a19:publish
call .\gradlew.bat :characteristic:u2a1c:publish
call .\gradlew.bat :characteristic:u2a1d:publish
call .\gradlew.bat :characteristic:u2a1e:publish
call .\gradlew.bat :characteristic:u2a21:publish
call .\gradlew.bat :characteristic:u2a22:publish
call .\gradlew.bat :characteristic:u2a23:publish
call .\gradlew.bat :characteristic:u2a24:publish
call .\gradlew.bat :characteristic:u2a25:publish
call .\gradlew.bat :characteristic:u2a26:publish
call .\gradlew.bat :characteristic:u2a27:publish
call .\gradlew.bat :characteristic:u2a28:publish
call .\gradlew.bat :characteristic:u2a29:publish
call .\gradlew.bat :characteristic:u2a2a:publish
call .\gradlew.bat :characteristic:u2a2b:publish
call .\gradlew.bat :characteristic:u2a2c:publish
call .\gradlew.bat :characteristic:u2a31:publish
call .\gradlew.bat :characteristic:u2a32:publish
call .\gradlew.bat :characteristic:u2a33:publish
call .\gradlew.bat :characteristic:u2a34:publish
call .\gradlew.bat :characteristic:u2a35:publish
call .\gradlew.bat :characteristic:u2a36:publish
call .\gradlew.bat :characteristic:u2a37:publish
call .\gradlew.bat :characteristic:u2a38:publish
call .\gradlew.bat :characteristic:u2a39:publish
call .\gradlew.bat :characteristic:u2a3f:publish
call .\gradlew.bat :characteristic:u2a40:publish
call .\gradlew.bat :characteristic:u2a41:publish
call .\gradlew.bat :characteristic:u2a42:publish
call .\gradlew.bat :characteristic:u2a43:publish
call .\gradlew.bat :characteristic:u2a44:publish
call .\gradlew.bat :characteristic:u2a45:publish
call .\gradlew.bat :characteristic:u2a46:publish
call .\gradlew.bat :characteristic:u2a47:publish
call .\gradlew.bat :characteristic:u2a48:publish
call .\gradlew.bat :characteristic:u2a49:publish
call .\gradlew.bat :characteristic:u2a4a:publish
call .\gradlew.bat :characteristic:u2a4b:publish
call .\gradlew.bat :characteristic:u2a4c:publish
call .\gradlew.bat :characteristic:u2a4d:publish
call .\gradlew.bat :characteristic:u2a4e:publish
call .\gradlew.bat :characteristic:u2a4f:publish
call .\gradlew.bat :characteristic:u2a50:publish
call .\gradlew.bat :characteristic:u2a51:publish
call .\gradlew.bat :characteristic:u2a52:publish
call .\gradlew.bat :characteristic:u2a53:publish
call .\gradlew.bat :characteristic:u2a54:publish
call .\gradlew.bat :characteristic:u2a55:publish
call .\gradlew.bat :characteristic:u2a56:publish
call .\gradlew.bat :characteristic:u2a58:publish
call .\gradlew.bat :characteristic:u2a5a:publish
call .\gradlew.bat :characteristic:u2a5b:publish
call .\gradlew.bat :characteristic:u2a5c:publish
call .\gradlew.bat :characteristic:u2a5d:publish
call .\gradlew.bat :characteristic:u2a5e:publish
call .\gradlew.bat :characteristic:u2a5f:publish
call .\gradlew.bat :characteristic:u2a60:publish
call .\gradlew.bat :characteristic:u2a63:publish
call .\gradlew.bat :characteristic:u2a64:publish
call .\gradlew.bat :characteristic:u2a65:publish
call .\gradlew.bat :characteristic:u2a66:publish
call .\gradlew.bat :characteristic:u2a67:publish
call .\gradlew.bat :characteristic:u2a68:publish
call .\gradlew.bat :characteristic:u2a69:publish
call .\gradlew.bat :characteristic:u2a6a:publish
call .\gradlew.bat :characteristic:u2a6b:publish
call .\gradlew.bat :characteristic:u2a6c:publish
call .\gradlew.bat :characteristic:u2a6d:publish
call .\gradlew.bat :characteristic:u2a6e:publish
call .\gradlew.bat :characteristic:u2a6f:publish
call .\gradlew.bat :characteristic:u2a70:publish
call .\gradlew.bat :characteristic:u2a71:publish
call .\gradlew.bat :characteristic:u2a72:publish
call .\gradlew.bat :characteristic:u2a73:publish
call .\gradlew.bat :characteristic:u2a74:publish
call .\gradlew.bat :characteristic:u2a75:publish
call .\gradlew.bat :characteristic:u2a76:publish
call .\gradlew.bat :characteristic:u2a77:publish
call .\gradlew.bat :characteristic:u2a78:publish
call .\gradlew.bat :characteristic:u2a79:publish
call .\gradlew.bat :characteristic:u2a7a:publish
call .\gradlew.bat :characteristic:u2a7b:publish
call .\gradlew.bat :characteristic:u2a7d:publish
call .\gradlew.bat :characteristic:u2a7e:publish
call .\gradlew.bat :characteristic:u2a7f:publish
call .\gradlew.bat :characteristic:u2a80:publish
call .\gradlew.bat :characteristic:u2a81:publish
call .\gradlew.bat :characteristic:u2a82:publish
call .\gradlew.bat :characteristic:u2a83:publish
call .\gradlew.bat :characteristic:u2a84:publish
call .\gradlew.bat :characteristic:u2a85:publish
call .\gradlew.bat :characteristic:u2a86:publish
call .\gradlew.bat :characteristic:u2a87:publish
call .\gradlew.bat :characteristic:u2a88:publish
call .\gradlew.bat :characteristic:u2a89:publish
call .\gradlew.bat :characteristic:u2a8a:publish
call .\gradlew.bat :characteristic:u2a8b:publish
call .\gradlew.bat :characteristic:u2a8c:publish
call .\gradlew.bat :characteristic:u2a8d:publish
call .\gradlew.bat :characteristic:u2a8e:publish
call .\gradlew.bat :characteristic:u2a8f:publish
call .\gradlew.bat :characteristic:u2a90:publish
call .\gradlew.bat :characteristic:u2a91:publish
call .\gradlew.bat :characteristic:u2a92:publish
call .\gradlew.bat :characteristic:u2a93:publish
call .\gradlew.bat :characteristic:u2a94:publish
call .\gradlew.bat :characteristic:u2a95:publish
call .\gradlew.bat :characteristic:u2a96:publish
call .\gradlew.bat :characteristic:u2a97:publish
call .\gradlew.bat :characteristic:u2a98:publish
call .\gradlew.bat :characteristic:u2a99:publish
call .\gradlew.bat :characteristic:u2a9a:publish
call .\gradlew.bat :characteristic:u2a9b:publish
call .\gradlew.bat :characteristic:u2a9c:publish
call .\gradlew.bat :characteristic:u2a9d:publish
call .\gradlew.bat :characteristic:u2a9e:publish
call .\gradlew.bat :characteristic:u2a9f:publish
call .\gradlew.bat :characteristic:u2aa0:publish
call .\gradlew.bat :characteristic:u2aa1:publish
call .\gradlew.bat :characteristic:u2aa2:publish
call .\gradlew.bat :characteristic:u2aa3:publish
call .\gradlew.bat :characteristic:u2aa4:publish
call .\gradlew.bat :characteristic:u2aa5:publish
call .\gradlew.bat :characteristic:u2aa6:publish
call .\gradlew.bat :characteristic:u2aa7:publish
call .\gradlew.bat :characteristic:u2aa8:publish
call .\gradlew.bat :characteristic:u2aa9:publish
call .\gradlew.bat :characteristic:u2aaa:publish
call .\gradlew.bat :characteristic:u2aab:publish
call .\gradlew.bat :characteristic:u2aac:publish
call .\gradlew.bat :characteristic:u2aad:publish
call .\gradlew.bat :characteristic:u2aae:publish
call .\gradlew.bat :characteristic:u2aaf:publish
call .\gradlew.bat :characteristic:u2ab0:publish
call .\gradlew.bat :characteristic:u2ab1:publish
call .\gradlew.bat :characteristic:u2ab2:publish
call .\gradlew.bat :characteristic:u2ab3:publish
call .\gradlew.bat :characteristic:u2ab4:publish
call .\gradlew.bat :characteristic:u2ab5:publish
call .\gradlew.bat :characteristic:u2ab6:publish
call .\gradlew.bat :characteristic:u2ab7:publish
call .\gradlew.bat :characteristic:u2ab8:publish
call .\gradlew.bat :characteristic:u2ab9:publish
call .\gradlew.bat :characteristic:u2aba:publish
call .\gradlew.bat :characteristic:u2abb:publish
call .\gradlew.bat :characteristic:u2abc:publish
call .\gradlew.bat :characteristic:u2abd:publish
call .\gradlew.bat :characteristic:u2abe:publish
call .\gradlew.bat :characteristic:u2abf:publish
call .\gradlew.bat :characteristic:u2ac0:publish
call .\gradlew.bat :characteristic:u2ac1:publish
call .\gradlew.bat :characteristic:u2ac2:publish
call .\gradlew.bat :characteristic:u2ac3:publish
call .\gradlew.bat :characteristic:u2ac4:publish
call .\gradlew.bat :characteristic:u2ac5:publish
call .\gradlew.bat :characteristic:u2ac6:publish
call .\gradlew.bat :characteristic:u2ac7:publish
call .\gradlew.bat :characteristic:u2ac8:publish
call .\gradlew.bat :characteristic:u2ac9:publish
call .\gradlew.bat :characteristic:u2aca:publish
call .\gradlew.bat :characteristic:u2acb:publish
call .\gradlew.bat :characteristic:u2acc:publish
call .\gradlew.bat :characteristic:u2acd:publish
call .\gradlew.bat :characteristic:u2ace:publish
call .\gradlew.bat :characteristic:u2acf:publish
call .\gradlew.bat :characteristic:u2ad0:publish
call .\gradlew.bat :characteristic:u2ad1:publish
call .\gradlew.bat :characteristic:u2ad2:publish
call .\gradlew.bat :characteristic:u2ad3:publish
call .\gradlew.bat :characteristic:u2ad4:publish
call .\gradlew.bat :characteristic:u2ad5:publish
call .\gradlew.bat :characteristic:u2ad6:publish
call .\gradlew.bat :characteristic:u2ad7:publish
call .\gradlew.bat :characteristic:u2ad8:publish
call .\gradlew.bat :characteristic:u2ad9:publish
call .\gradlew.bat :characteristic:u2ada:publish
call .\gradlew.bat :characteristic:u2adb:publish
call .\gradlew.bat :characteristic:u2adc:publish
call .\gradlew.bat :characteristic:u2add:publish
call .\gradlew.bat :characteristic:u2ade:publish
call .\gradlew.bat :characteristic:u2ae0:publish
call .\gradlew.bat :characteristic:u2ae1:publish
call .\gradlew.bat :characteristic:u2ae2:publish
call .\gradlew.bat :characteristic:u2ae3:publish
call .\gradlew.bat :characteristic:u2ae4:publish
call .\gradlew.bat :characteristic:u2ae5:publish
call .\gradlew.bat :characteristic:u2ae6:publish
call .\gradlew.bat :characteristic:u2ae7:publish
call .\gradlew.bat :characteristic:u2ae8:publish
call .\gradlew.bat :characteristic:u2ae9:publish
call .\gradlew.bat :characteristic:u2aea:publish
call .\gradlew.bat :characteristic:u2aeb:publish
call .\gradlew.bat :characteristic:u2aec:publish
call .\gradlew.bat :characteristic:u2aed:publish
call .\gradlew.bat :characteristic:u2aee:publish
call .\gradlew.bat :characteristic:u2aef:publish
call .\gradlew.bat :characteristic:u2af0:publish
call .\gradlew.bat :characteristic:u2af1:publish
call .\gradlew.bat :characteristic:u2af2:publish
call .\gradlew.bat :characteristic:u2af3:publish
call .\gradlew.bat :characteristic:u2af4:publish
call .\gradlew.bat :characteristic:u2af5:publish
call .\gradlew.bat :characteristic:u2af6:publish
call .\gradlew.bat :characteristic:u2af7:publish
call .\gradlew.bat :characteristic:u2af8:publish
call .\gradlew.bat :characteristic:u2af9:publish
call .\gradlew.bat :characteristic:u2afa:publish
call .\gradlew.bat :characteristic:u2afb:publish
call .\gradlew.bat :characteristic:u2afc:publish
call .\gradlew.bat :characteristic:u2afd:publish
call .\gradlew.bat :characteristic:u2afe:publish
call .\gradlew.bat :characteristic:u2aff:publish
call .\gradlew.bat :characteristic:u2b00:publish
call .\gradlew.bat :characteristic:u2b01:publish
call .\gradlew.bat :characteristic:u2b02:publish
call .\gradlew.bat :characteristic:u2b03:publish
call .\gradlew.bat :characteristic:u2b04:publish
call .\gradlew.bat :characteristic:u2b05:publish
call .\gradlew.bat :characteristic:u2b06:publish
call .\gradlew.bat :characteristic:u2b07:publish
call .\gradlew.bat :characteristic:u2b08:publish
call .\gradlew.bat :characteristic:u2b09:publish
call .\gradlew.bat :characteristic:u2b0a:publish
call .\gradlew.bat :characteristic:u2b0b:publish
call .\gradlew.bat :characteristic:u2b0c:publish
call .\gradlew.bat :characteristic:u2b0d:publish
call .\gradlew.bat :characteristic:u2b0e:publish
call .\gradlew.bat :characteristic:u2b0f:publish
call .\gradlew.bat :characteristic:u2b10:publish
call .\gradlew.bat :characteristic:u2b11:publish
call .\gradlew.bat :characteristic:u2b12:publish
call .\gradlew.bat :characteristic:u2b13:publish
call .\gradlew.bat :characteristic:u2b14:publish
call .\gradlew.bat :characteristic:u2b15:publish
call .\gradlew.bat :characteristic:u2b16:publish
call .\gradlew.bat :characteristic:u2b17:publish
call .\gradlew.bat :characteristic:u2b18:publish
call .\gradlew.bat :characteristic:u2b19:publish
call .\gradlew.bat :characteristic:u2b1a:publish
call .\gradlew.bat :characteristic:u2b1b:publish
call .\gradlew.bat :characteristic:u2b1c:publish
call .\gradlew.bat :characteristic:u2b1d:publish
call .\gradlew.bat :characteristic:u2b1e:publish
call .\gradlew.bat :characteristic:u2b1f:publish
call .\gradlew.bat :characteristic:u2b20:publish
call .\gradlew.bat :characteristic:u2b21:publish
call .\gradlew.bat :characteristic:u2b22:publish
call .\gradlew.bat :characteristic:u2b23:publish
call .\gradlew.bat :characteristic:u2b24:publish
call .\gradlew.bat :characteristic:u2b25:publish
call .\gradlew.bat :characteristic:u2b26:publish
call .\gradlew.bat :characteristic:u2b27:publish
call .\gradlew.bat :characteristic:u2b28:publish
call .\gradlew.bat :characteristic:u2b29:publish
call .\gradlew.bat :characteristic:u2b2a:publish
call .\gradlew.bat :characteristic:u2b2b:publish
call .\gradlew.bat :characteristic:u2b2c:publish
call .\gradlew.bat :characteristic:u2b2d:publish
call .\gradlew.bat :characteristic:u2b2e:publish
call .\gradlew.bat :characteristic:u2b2f:publish
call .\gradlew.bat :characteristic:u2b30:publish
call .\gradlew.bat :characteristic:u2b31:publish
call .\gradlew.bat :characteristic:u2b32:publish
call .\gradlew.bat :characteristic:u2b33:publish
call .\gradlew.bat :characteristic:u2b34:publish
call .\gradlew.bat :characteristic:u2b35:publish
call .\gradlew.bat :characteristic:u2b36:publish
call .\gradlew.bat :characteristic:u2b37:publish
call .\gradlew.bat :characteristic:u2b38:publish
call .\gradlew.bat :characteristic:u2b39:publish
call .\gradlew.bat :characteristic:u2b3a:publish
call .\gradlew.bat :characteristic:u2b3b:publish
call .\gradlew.bat :characteristic:u2b3c:publish
call .\gradlew.bat :characteristic:u2b3d:publish
call .\gradlew.bat :characteristic:u2b3e:publish
call .\gradlew.bat :characteristic:u2b3f:publish
call .\gradlew.bat :characteristic:u2b40:publish
call .\gradlew.bat :characteristic:u2b41:publish
call .\gradlew.bat :characteristic:u2b42:publish
call .\gradlew.bat :characteristic:u2b43:publish
call .\gradlew.bat :characteristic:u2b44:publish
call .\gradlew.bat :characteristic:u2b45:publish
call .\gradlew.bat :characteristic:u2b46:publish
call .\gradlew.bat :characteristic:u2b47:publish
call .\gradlew.bat :characteristic:u2b48:publish
call .\gradlew.bat :characteristic:u2b49:publish
call .\gradlew.bat :characteristic:u2b4a:publish
call .\gradlew.bat :characteristic:u2b4b:publish
call .\gradlew.bat :characteristic:u2b4c:publish
call .\gradlew.bat :characteristic:u2b4d:publish
call .\gradlew.bat :characteristic:u2b4e:publish
call .\gradlew.bat :characteristic:u2b4f:publish
call .\gradlew.bat :characteristic:u2b50:publish
call .\gradlew.bat :characteristic:u2b51:publish
call .\gradlew.bat :characteristic:u2b77:publish
call .\gradlew.bat :characteristic:u2b78:publish
call .\gradlew.bat :characteristic:u2b79:publish
call .\gradlew.bat :characteristic:u2b7a:publish
call .\gradlew.bat :characteristic:u2b7b:publish
call .\gradlew.bat :characteristic:u2b7c:publish
call .\gradlew.bat :characteristic:u2b7d:publish
call .\gradlew.bat :characteristic:u2b7e:publish
call .\gradlew.bat :characteristic:u2b7f:publish
call .\gradlew.bat :characteristic:u2b80:publish
call .\gradlew.bat :characteristic:u2b81:publish
call .\gradlew.bat :characteristic:u2b82:publish
call .\gradlew.bat :characteristic:u2b83:publish
call .\gradlew.bat :characteristic:u2b84:publish
call .\gradlew.bat :characteristic:u2b85:publish
call .\gradlew.bat :characteristic:u2b86:publish
call .\gradlew.bat :characteristic:u2b87:publish
call .\gradlew.bat :characteristic:u2b88:publish
call .\gradlew.bat :characteristic:u2b89:publish
call .\gradlew.bat :characteristic:u2b8a:publish
call .\gradlew.bat :characteristic:u2b8c:publish
call .\gradlew.bat :characteristic:u2b8d:publish
call .\gradlew.bat :characteristic:u2b8e:publish
call .\gradlew.bat :characteristic:u2b8f:publish
call .\gradlew.bat :characteristic:u2b90:publish
call .\gradlew.bat :characteristic:u2b91:publish
call .\gradlew.bat :characteristic:u2b92:publish
call .\gradlew.bat :characteristic:u2b93:publish
call .\gradlew.bat :characteristic:u2b94:publish
call .\gradlew.bat :characteristic:u2b95:publish
call .\gradlew.bat :characteristic:u2b96:publish
call .\gradlew.bat :characteristic:u2b97:publish
call .\gradlew.bat :characteristic:u2b98:publish
call .\gradlew.bat :characteristic:u2b99:publish
call .\gradlew.bat :characteristic:u2b9a:publish
call .\gradlew.bat :characteristic:u2b9b:publish
call .\gradlew.bat :characteristic:u2b9c:publish
call .\gradlew.bat :characteristic:u2b9d:publish
call .\gradlew.bat :characteristic:u2b9e:publish
call .\gradlew.bat :characteristic:u2b9f:publish
call .\gradlew.bat :characteristic:u2ba0:publish
call .\gradlew.bat :characteristic:u2ba1:publish
call .\gradlew.bat :characteristic:u2ba2:publish
call .\gradlew.bat :characteristic:u2ba3:publish
call .\gradlew.bat :characteristic:u2ba4:publish
call .\gradlew.bat :characteristic:u2ba5:publish
call .\gradlew.bat :characteristic:u2ba6:publish
call .\gradlew.bat :characteristic:u2ba7:publish
call .\gradlew.bat :characteristic:u2ba8:publish
call .\gradlew.bat :characteristic:u2ba9:publish
call .\gradlew.bat :characteristic:u2baa:publish
call .\gradlew.bat :characteristic:u2bab:publish
call .\gradlew.bat :characteristic:u2bac:publish
call .\gradlew.bat :characteristic:u2bad:publish
call .\gradlew.bat :characteristic:u2bae:publish
call .\gradlew.bat :characteristic:u2baf:publish
call .\gradlew.bat :characteristic:u2bb0:publish
call .\gradlew.bat :characteristic:u2bb1:publish
call .\gradlew.bat :characteristic:u2bb2:publish
call .\gradlew.bat :characteristic:u2bb3:publish
call .\gradlew.bat :characteristic:u2bb4:publish
call .\gradlew.bat :characteristic:u2bb5:publish
call .\gradlew.bat :characteristic:u2bb6:publish
call .\gradlew.bat :characteristic:u2bb7:publish
call .\gradlew.bat :characteristic:u2bb8:publish
call .\gradlew.bat :characteristic:u2bb9:publish
call .\gradlew.bat :characteristic:u2bba:publish
call .\gradlew.bat :characteristic:u2bbb:publish
call .\gradlew.bat :characteristic:u2bbc:publish
call .\gradlew.bat :characteristic:u2bbd:publish
call .\gradlew.bat :characteristic:u2bbe:publish
call .\gradlew.bat :characteristic:u2bbf:publish
call .\gradlew.bat :characteristic:u2bc0:publish
call .\gradlew.bat :characteristic:u2bc1:publish
call .\gradlew.bat :characteristic:u2bc2:publish
call .\gradlew.bat :characteristic:u2bc3:publish
call .\gradlew.bat :characteristic:u2bc4:publish
call .\gradlew.bat :characteristic:u2bc5:publish
call .\gradlew.bat :characteristic:u2bc6:publish
call .\gradlew.bat :characteristic:u2bc7:publish
call .\gradlew.bat :characteristic:u2bc8:publish
call .\gradlew.bat :characteristic:u2bc9:publish
call .\gradlew.bat :characteristic:u2bca:publish
call .\gradlew.bat :characteristic:u2bcb:publish
call .\gradlew.bat :characteristic:u2bcc:publish
call .\gradlew.bat :characteristic:u2bcd:publish
call .\gradlew.bat :characteristic:u2bce:publish
call .\gradlew.bat :characteristic:u2bcf:publish
call .\gradlew.bat :characteristic:u2bd0:publish
call .\gradlew.bat :characteristic:u2bd1:publish
call .\gradlew.bat :characteristic:u2bd2:publish
call .\gradlew.bat :characteristic:u2bd3:publish
call .\gradlew.bat :characteristic:u2bd4:publish
call .\gradlew.bat :characteristic:u2bd5:publish
call .\gradlew.bat :characteristic:u2bd6:publish
call .\gradlew.bat :characteristic:u2bd7:publish
call .\gradlew.bat :characteristic:u2bd8:publish
call .\gradlew.bat :characteristic:u2bd9:publish
call .\gradlew.bat :characteristic:u2bda:publish
call .\gradlew.bat :characteristic:u2bdb:publish
call .\gradlew.bat :characteristic:u2bdc:publish
call .\gradlew.bat :characteristic:u2bde:publish
call .\gradlew.bat :characteristic:u2bdf:publish
call .\gradlew.bat :characteristic:u2be0:publish
call .\gradlew.bat :characteristic:u2be1:publish
call .\gradlew.bat :characteristic:u2be2:publish
call .\gradlew.bat :characteristic:u2be3:publish
call .\gradlew.bat :characteristic:u2be4:publish
call .\gradlew.bat :characteristic:u2be5:publish
call .\gradlew.bat :characteristic:u2be6:publish
call .\gradlew.bat :characteristic:u2be7:publish
call .\gradlew.bat :characteristic:u2be8:publish
call .\gradlew.bat :characteristic:u2be9:publish
call .\gradlew.bat :characteristic:u2bea:publish
call .\gradlew.bat :characteristic:u2beb:publish
call .\gradlew.bat :characteristic:u2bec:publish
call .\gradlew.bat :characteristic:u2bed:publish
call .\gradlew.bat :characteristic:u2bee:publish
call .\gradlew.bat :characteristic:u2bef:publish
call .\gradlew.bat :characteristic:u2bf0:publish
call .\gradlew.bat :characteristic:u2bf5:publish
call .\gradlew.bat :characteristic:u2bf6:publish
call .\gradlew.bat :characteristic:u2bf7:publish
call .\gradlew.bat :characteristic:u2bf8:publish
call .\gradlew.bat :characteristic:u2bf9:publish
call .\gradlew.bat :characteristic:u2bfa:publish
call .\gradlew.bat :characteristic:u2bfb:publish
call .\gradlew.bat :characteristic:u2bfc:publish
call .\gradlew.bat :characteristic:u2bfd:publish
call .\gradlew.bat :characteristic:u2bfe:publish
call .\gradlew.bat :characteristic:publish

call .\gradlew.bat :library-handler:publish
call .\gradlew.bat :library-central:publish
call .\gradlew.bat :library-peripheral:publish

call .\gradlew.bat :test:publish
call .\gradlew.bat :test:central:publish
call .\gradlew.bat :test:peripheral:publish

call .\gradlew.bat :service:aios:publish
call .\gradlew.bat :service:aios:central:publish
call .\gradlew.bat :service:aios:peripheral:publish
call .\gradlew.bat :service:ans:publish
call .\gradlew.bat :service:ans:central:publish
call .\gradlew.bat :service:ans:peripheral:publish
call .\gradlew.bat :service:bas:publish
call .\gradlew.bat :service:bas:central:publish
call .\gradlew.bat :service:bas:peripheral:publish
call .\gradlew.bat :service:bcs:publish
call .\gradlew.bat :service:bcs:central:publish
call .\gradlew.bat :service:bcs:peripheral:publish
call .\gradlew.bat :service:bls:publish
call .\gradlew.bat :service:bls:central:publish
call .\gradlew.bat :service:bls:peripheral:publish
call .\gradlew.bat :service:bms:publish
call .\gradlew.bat :service:bms:central:publish
call .\gradlew.bat :service:bms:peripheral:publish
call .\gradlew.bat :service:central:publish
call .\gradlew.bat :service:cps:publish
call .\gradlew.bat :service:cps:central:publish
call .\gradlew.bat :service:cps:peripheral:publish
call .\gradlew.bat :service:cscs:publish
call .\gradlew.bat :service:cscs:central:publish
call .\gradlew.bat :service:cscs:peripheral:publish
call .\gradlew.bat :service:cts:publish
call .\gradlew.bat :service:cts:central:publish
call .\gradlew.bat :service:cts:peripheral:publish
call .\gradlew.bat :service:peripheral:publish
call .\gradlew.bat :service:dis:publish
call .\gradlew.bat :service:dis:central:publish
call .\gradlew.bat :service:dis:peripheral:publish
call .\gradlew.bat :service:ess:publish
call .\gradlew.bat :service:ess:central:publish
call .\gradlew.bat :service:ess:peripheral:publish
call .\gradlew.bat :service:ftms:publish
call .\gradlew.bat :service:ftms:central:publish
call .\gradlew.bat :service:ftms:peripheral:publish
call .\gradlew.bat :service:gap:publish
call .\gradlew.bat :service:gap:central:publish
call .\gradlew.bat :service:gap:peripheral:publish
call .\gradlew.bat :service:gatt:publish
call .\gradlew.bat :service:gatt:central:publish
call .\gradlew.bat :service:gatt:peripheral:publish
call .\gradlew.bat :service:hrs:publish
call .\gradlew.bat :service:hrs:central:publish
call .\gradlew.bat :service:hrs:peripheral:publish
call .\gradlew.bat :service:hts:publish
call .\gradlew.bat :service:hts:central:publish
call .\gradlew.bat :service:hts:peripheral:publish
call .\gradlew.bat :service:ias:publish
call .\gradlew.bat :service:ias:central:publish
call .\gradlew.bat :service:ias:peripheral:publish
call .\gradlew.bat :service:lls:publish
call .\gradlew.bat :service:lls:central:publish
call .\gradlew.bat :service:lls:peripheral:publish
call .\gradlew.bat :service:lns:publish
call .\gradlew.bat :service:lns:central:publish
call .\gradlew.bat :service:lns:peripheral:publish
call .\gradlew.bat :service:ndcs:publish
call .\gradlew.bat :service:ndcs:central:publish
call .\gradlew.bat :service:ndcs:peripheral:publish
call .\gradlew.bat :service:pass:publish
call .\gradlew.bat :service:pass:central:publish
call .\gradlew.bat :service:pass:peripheral:publish
call .\gradlew.bat :service:rscs:publish
call .\gradlew.bat :service:rscs:central:publish
call .\gradlew.bat :service:rscs:peripheral:publish
call .\gradlew.bat :service:rcs:publish
call .\gradlew.bat :service:rcs:central:publish
call .\gradlew.bat :service:rcs:peripheral:publish
call .\gradlew.bat :service:rtus:publish
call .\gradlew.bat :service:rtus:central:publish
call .\gradlew.bat :service:rtus:peripheral:publish
call .\gradlew.bat :service:scps:publish
call .\gradlew.bat :service:scps:central:publish
call .\gradlew.bat :service:scps:peripheral:publish
call .\gradlew.bat :service:tps:publish
call .\gradlew.bat :service:tps:central:publish
call .\gradlew.bat :service:tps:peripheral:publish
call .\gradlew.bat :service:uds:publish
call .\gradlew.bat :service:uds:central:publish
call .\gradlew.bat :service:uds:peripheral:publish
call .\gradlew.bat :service:wss:publish
call .\gradlew.bat :service:wss:central:publish
call .\gradlew.bat :service:wss:peripheral:publish
call .\gradlew.bat :service:publish

call .\gradlew.bat :profile:central:publish
call .\gradlew.bat :profile:peripheral:publish
call .\gradlew.bat :profile:aiop:publish
call .\gradlew.bat :profile:aiop:central:publish
call .\gradlew.bat :profile:aiop:peripheral:publish
call .\gradlew.bat :profile:anp:publish
call .\gradlew.bat :profile:anp:central:publish
call .\gradlew.bat :profile:anp:peripheral:publish
call .\gradlew.bat :profile:blp:publish
call .\gradlew.bat :profile:blp:central:publish
call .\gradlew.bat :profile:blp:peripheral:publish
call .\gradlew.bat :profile:cpp:publish
call .\gradlew.bat :profile:cpp:central:publish
call .\gradlew.bat :profile:cpp:peripheral:publish
call .\gradlew.bat :profile:cscp:publish
call .\gradlew.bat :profile:cscp:central:publish
call .\gradlew.bat :profile:cscp:peripheral:publish
call .\gradlew.bat :profile:esp:publish
call .\gradlew.bat :profile:esp:central:publish
call .\gradlew.bat :profile:esp:peripheral:publish
call .\gradlew.bat :profile:fmp:publish
call .\gradlew.bat :profile:fmp:central:publish
call .\gradlew.bat :profile:fmp:peripheral:publish
call .\gradlew.bat :profile:ftmp:publish
call .\gradlew.bat :profile:ftmp:central:publish
call .\gradlew.bat :profile:ftmp:peripheral:publish
call .\gradlew.bat :profile:hrp:publish
call .\gradlew.bat :profile:hrp:central:publish
call .\gradlew.bat :profile:hrp:peripheral:publish
call .\gradlew.bat :profile:htp:publish
call .\gradlew.bat :profile:htp:central:publish
call .\gradlew.bat :profile:htp:peripheral:publish
call .\gradlew.bat :profile:lnp:publish
call .\gradlew.bat :profile:lnp:central:publish
call .\gradlew.bat :profile:lnp:peripheral:publish
call .\gradlew.bat :profile:pasp:publish
call .\gradlew.bat :profile:pasp:central:publish
call .\gradlew.bat :profile:pasp:peripheral:publish
call .\gradlew.bat :profile:pxp:publish
call .\gradlew.bat :profile:pxp:central:publish
call .\gradlew.bat :profile:pxp:peripheral:publish
call .\gradlew.bat :profile:rcp:publish
call .\gradlew.bat :profile:rcp:central:publish
call .\gradlew.bat :profile:rcp:peripheral:publish
call .\gradlew.bat :profile:rscp:publish
call .\gradlew.bat :profile:rscp:central:publish
call .\gradlew.bat :profile:rscp:peripheral:publish
call .\gradlew.bat :profile:scpp:publish
call .\gradlew.bat :profile:scpp:central:publish
call .\gradlew.bat :profile:scpp:peripheral:publish
call .\gradlew.bat :profile:tip:publish
call .\gradlew.bat :profile:tip:central:publish
call .\gradlew.bat :profile:tip:peripheral:publish
call .\gradlew.bat :profile:wsp:publish
call .\gradlew.bat :profile:wsp:central:publish
call .\gradlew.bat :profile:wsp:peripheral:publish
call .\gradlew.bat :profile:publish